### ISSUE TITLE
feat: Sorting Options for Galleries Component

### ISSUE THREAD

**Issue by seanjkanderson** [sqwk/oct-gallery#1]
Hi there,

Is there documentation for ordering the set of galleries? Just wondering what the set of keywords are for gallery ordering say alphanumerically by gallery name or by slug or what have you.

Cheers

**Comment by sqwk** [comment]
There is currently no such functionality. (Related, in the backlog and also not yet implemented: Pagination for the galleries list)

However, it should be very simple to implement yourself, by overriding the galleries component: Insert it into your CMS page, partial etc., move your cursor so that it is 'inside' the word component and click on the little branch icon at the bottom right of the code editor. `galleries` is just a variable. You can implement your own filtering, sorting etc. based on any logic that you want.

Note that this is not ideal, but it will work. A better way would be to handle it as part of the plugin based on optional component options, ideally directly via the eloquent model.

**Comment by seanjkanderson** [comment]
Thanks, I had thought I read somewhere in your docs that it was possible, so thanks for clarifying that.

Cheers.
